//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fff.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CalcClear {
            get {
                return ResourceManager.GetString("CalcClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string CalcSum {
            get {
                return ResourceManager.GetString("CalcSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUWANIE BAZY.
        /// </summary>
        public static string DatabaseErase {
            get {
                return ResourceManager.GetString("DatabaseErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz datę.
        /// </summary>
        public static string DateChoose {
            get {
                return ResourceManager.GetString("DateChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko liczby.
        /// </summary>
        public static string DecimalOnly {
            get {
                return ResourceManager.GetString("DecimalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięte.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ściągnij.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ściągnij bazę.
        /// </summary>
        public static string DownloadDatabaseExpand {
            get {
                return ResourceManager.GetString("DownloadDatabaseExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zduplikowane kolumny, pamiętaj o aliasach.
        /// </summary>
        public static string DuplCol {
            get {
                return ResourceManager.GetString("DuplCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść bazę.
        /// </summary>
        public static string EraseDatabase {
            get {
                return ResourceManager.GetString("EraseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydarzenie.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydarzenia.
        /// </summary>
        public static string EventAddTip {
            get {
                return ResourceManager.GetString("EventAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz dzień.
        /// </summary>
        public static string EventCalendarTip {
            get {
                return ResourceManager.GetString("EventCalendarTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz osoby.
        /// </summary>
        public static string EventExpPersonTip {
            get {
                return ResourceManager.GetString("EventExpPersonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę wydarzenia.
        /// </summary>
        public static string EventFill {
            get {
                return ResourceManager.GetString("EventFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe wydarzenie.
        /// </summary>
        public static string EventNew {
            get {
                return ResourceManager.GetString("EventNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydarzenia.
        /// </summary>
        public static string EventPageTitle {
            get {
                return ResourceManager.GetString("EventPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryp solo.
        /// </summary>
        public static string EventSoloCheck {
            get {
                return ResourceManager.GetString("EventSoloCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę wydatku.
        /// </summary>
        public static string ExpenseFill {
            get {
                return ResourceManager.GetString("ExpenseFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie pola muszą być wypełnione.
        /// </summary>
        public static string FieldsEmpty {
            get {
                return ResourceManager.GetString("FieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login musi mieć przynajmniej 6 znaków.
        /// </summary>
        public static string LoginFormat {
            get {
                return ResourceManager.GetString("LoginFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny login lub hasło.
        /// </summary>
        public static string LoginPassWrond {
            get {
                return ResourceManager.GetString("LoginPassWrond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainPageToolTipAbout {
            get {
                return ResourceManager.GetString("MainPageToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydarzenia.
        /// </summary>
        public static string MainPageToolTipEvent {
            get {
                return ResourceManager.GetString("MainPageToolTipEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oosby.
        /// </summary>
        public static string MainPageToolTipPerson {
            get {
                return ResourceManager.GetString("MainPageToolTipPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty użytkownika.
        /// </summary>
        public static string MainPageToolTipReports {
            get {
                return ResourceManager.GetString("MainPageToolTipReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string MainPageToolTipSettings {
            get {
                return ResourceManager.GetString("MainPageToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowanie.
        /// </summary>
        public static string MainPageToolTipSummary {
            get {
                return ResourceManager.GetString("MainPageToolTipSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie pasują.
        /// </summary>
        public static string NotPasswords {
            get {
                return ResourceManager.GetString("NotPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć przynajmniej 6 znaków.
        /// </summary>
        public static string PassFormat {
            get {
                return ResourceManager.GetString("PassFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz płatnika.
        /// </summary>
        public static string PayerChoose {
            get {
                return ResourceManager.GetString("PayerChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj osobę.
        /// </summary>
        public static string PersonAddTip {
            get {
                return ResourceManager.GetString("PersonAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz osobę.
        /// </summary>
        public static string PersonChoose {
            get {
                return ResourceManager.GetString("PersonChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz osobę.
        /// </summary>
        public static string PersonFill {
            get {
                return ResourceManager.GetString("PersonFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa osoba.
        /// </summary>
        public static string PersonNew {
            get {
                return ResourceManager.GetString("PersonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz przynajmniej jedną osobę.
        /// </summary>
        public static string PersonOneChoose {
            get {
                return ResourceManager.GetString("PersonOneChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoby.
        /// </summary>
        public static string PersonPageTitle {
            get {
                return ResourceManager.GetString("PersonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W trybie solo możesz wybrać tylko jedną osobę.
        /// </summary>
        public static string PersonSoloChoode {
            get {
                return ResourceManager.GetString("PersonSoloChoode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz cenę.
        /// </summary>
        public static string PriceFill {
            get {
                return ResourceManager.GetString("PriceFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne zapytanie.
        /// </summary>
        public static string QueryWrong {
            get {
                return ResourceManager.GetString("QueryWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string RegisterExpand {
            get {
                return ResourceManager.GetString("RegisterExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku &apos;reports.xml&apos;.
        /// </summary>
        public static string ReportFileProblem {
            get {
                return ResourceManager.GetString("ReportFileProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Raporty.
        /// </summary>
        public static string ReportPageTitle {
            get {
                return ResourceManager.GetString("ReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należność.
        /// </summary>
        public static string ReportPersonHeaderDebtF {
            get {
                return ResourceManager.GetString("ReportPersonHeaderDebtF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dług.
        /// </summary>
        public static string ReportPersonHeaderDebtM {
            get {
                return ResourceManager.GetString("ReportPersonHeaderDebtM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własne wydatki.
        /// </summary>
        public static string ReportPersonHeaderOwn {
            get {
                return ResourceManager.GetString("ReportPersonHeaderOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydatek.
        /// </summary>
        public static string SaleAddTip {
            get {
                return ResourceManager.GetString("SaleAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupował.
        /// </summary>
        public static string SaleBuyerToolTip {
            get {
                return ResourceManager.GetString("SaleBuyerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwiń kalkulator.
        /// </summary>
        public static string SaleExpCalcTip {
            get {
                return ResourceManager.GetString("SaleExpCalcTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy wydatek.
        /// </summary>
        public static string SaleNewSale {
            get {
                return ResourceManager.GetString("SaleNewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki.
        /// </summary>
        public static string SalePageTitle {
            get {
                return ResourceManager.GetString("SalePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płacił.
        /// </summary>
        public static string SalePayerToolTip {
            get {
                return ResourceManager.GetString("SalePayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string SalePriceTip {
            get {
                return ResourceManager.GetString("SalePriceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozlicz.
        /// </summary>
        public static string Settle {
            get {
                return ResourceManager.GetString("Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zły ciąg.
        /// </summary>
        public static string StringWrong {
            get {
                return ResourceManager.GetString("StringWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowanie.
        /// </summary>
        public static string SummaryPageTitle {
            get {
                return ResourceManager.GetString("SummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij bazę.
        /// </summary>
        public static string UploadDatabaseExpand {
            get {
                return ResourceManager.GetString("UploadDatabaseExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem z plikiem XML.
        /// </summary>
        public static string XmlProblem {
            get {
                return ResourceManager.GetString("XmlProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliku bazy nie ma jeszcze na serwerze.
        /// </summary>
        public static string YetServerDatabase {
            get {
                return ResourceManager.GetString("YetServerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć bazę?.
        /// </summary>
        public static string YouAre {
            get {
                return ResourceManager.GetString("YouAre", resourceCulture);
            }
        }
    }
}
